Feat/mods
* feat(mods): add Modrinth-app like version switcher + more install button states

* fix: app_pojavlauncher/src/main/res/drawable/ic_swap_horiz.xml (forgot to hit Ctrl+S)

* ModItemAdapter.java:405: error: static declarations not allowed in inner classes private enum InstallButtonState { INSTALL, INSTALLED, UPDATE, DOWNGRADE }

* fix(mods): delete old jar on update/downgrade, fix collapsed switch-version dialog

* fix(mods): show all versions by default in switch-version dialog, add diagnostic logging

Signed-off-by: MaxJubayerYT <maxjubayergaming@gmail.com>

* fix(mods): use fixed-height content area in switch-version dialog instead of unreliable window resize

* fix(mods): sync switch-version dialog colors with active app theme

* fix(mods): hide incompatible versions by default in switch-version dialog

* refactor(mods): rebuild switch-version dialog + rows to match native app UI patterns

* fix(mods): match version row + dialog to native UI style, fix icons, remove cancel button

* fix(mods): Just use normal icons I gave up

* fix(mods): Nah I like the pixlated icons (made by @crex56)

---------

Signed-off-by: MaxJubayerYT <maxjubayergaming@gmail.com>